site_name: Robotický tábor-2021
site_url: https://example.com/
theme:
    name: material
    # name: bootstrap386
    palette:
        scheme: slate
        primary: deep orange
    language: cs
    # logo: assets/logo.png
    # favicon: images/favicon.png
    features:
        - navigation.expand
        - navigation.instant


docs_dir: gadgets

plugins:
    - awesome-pages
    # - literate-nav
    - search

nav:
    - index.md
    - Electron:
        - electron/README.md
        - electron/electron-lesson-1.md
        - electron/electron-lesson-2.md
        - electron/electron-lesson-3.md
    - Hrací kostka:
        - electronicDie/README.md
        - electronicDie/manual.md
    - Logic:
        - logic/README.md
        - logic/manual.md
    - RoboSvit:
        - roboSvit/README.md
        - roboSvit/manual.md
    - Pájecí výzva:
        - solderingChallenge/README.md
        - solderingChallenge/manual.md
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
      name: IREE Discord Server
    # - icon: fontawesome/brands/twitter
    #   link: 
    lightbox:
            gallery: true    