site_name: Robotický tábor-2021
site_url: https://example.com/
theme:
    name: material
    # name: bootstrap386
    palette:
        scheme: slate
        primary: deep orange
        accent: light green
    language: cs
    logo: assets/logo.png
    favicon: assets/logo180.png
    features:
        - navigation.expand
        - navigation.instant
        # - navigation.tracking
        # - navigation.instant
    custom_dir: overrides


docs_dir: gadgets

plugins:
    - awesome-pages
    - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
    - index.md
    - Electron:
        - electron/README.md
        - electron/electron-lesson-1.md
        - electron/electron-lesson-2.md
        - electron/electron-lesson-3.md
    - Hrací kostka:
        - electronicDie/README.md
        - electronicDie/manual.md
    - Logic:
        - logic/README.md
        - logic/manual.md
        - Programování:
            # - logic/code/example.md
            - logic/code/utils.md
            - logic/code/buttons.md
            - logic/code/display.md
            - logic/code/statusBar.md
            - logic/code/buzzer.md
            - logic/code/links.md
            - logic/code/projects.md
        - logic/examples.md
    - RoboSvit:
        - roboSvit/README.md
        - roboSvit/manual.md
    - Pájecí výzva:
        - solderingChallenge/README.md
        - solderingChallenge/manual.md
    - BlackBox:
        - blackBox/README.md
        - blackBox/manual.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
      name: IREE Discord Server
    # - icon: fontawesome/brands/twitter
    #   link:
    # lightbox:
    #         gallery: true

extra_javascript:
  - assets/highlight/highlight.min.js
  - assets/config.js
extra_css:
  - assets/highlight/default.min.css
  - assets/style.css